"""add platform profile and status suggestion

Revision ID: 0e6fbf22aa84
Revises: 17f15ed3896f
Create Date: 2026-02-17 17:36:26.334733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6fbf22aa84'
down_revision: Union[str, None] = '17f15ed3896f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
