"""add platform_profile and status_suggestion tables

Revision ID: 17f15ed3896f
Revises: 76bc83617402
Create Date: 2026-02-17 17:28:38.016480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '17f15ed3896f'
down_revision: Union[str, None] = '76bc83617402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platformprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applied_list_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform_name', name='uq_platformprofile_user_platform')
    )
    op.create_index(op.f('ix_platformprofile_platform_name'), 'platformprofile', ['platform_name'], unique=False)
    op.create_index(op.f('ix_platformprofile_user_id'), 'platformprofile', ['user_id'], unique=False)
    op.create_table('statussuggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('suggested_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statussuggestion_application_id'), 'statussuggestion', ['application_id'], unique=False)
    op.create_index(op.f('ix_statussuggestion_source_type'), 'statussuggestion', ['source_type'], unique=False)
    op.create_index(op.f('ix_statussuggestion_status'), 'statussuggestion', ['status'], unique=False)
    op.create_index(op.f('ix_statussuggestion_suggested_stage'), 'statussuggestion', ['suggested_stage'], unique=False)
    op.create_index(op.f('ix_statussuggestion_user_id'), 'statussuggestion', ['user_id'], unique=False)
    op.create_index('ix_suggestion_user_status', 'statussuggestion', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suggestion_user_status', table_name='statussuggestion')
    op.drop_index(op.f('ix_statussuggestion_user_id'), table_name='statussuggestion')
    op.drop_index(op.f('ix_statussuggestion_suggested_stage'), table_name='statussuggestion')
    op.drop_index(op.f('ix_statussuggestion_status'), table_name='statussuggestion')
    op.drop_index(op.f('ix_statussuggestion_source_type'), table_name='statussuggestion')
    op.drop_index(op.f('ix_statussuggestion_application_id'), table_name='statussuggestion')
    op.drop_table('statussuggestion')
    op.drop_index(op.f('ix_platformprofile_user_id'), table_name='platformprofile')
    op.drop_index(op.f('ix_platformprofile_platform_name'), table_name='platformprofile')
    op.drop_table('platformprofile')
    # ### end Alembic commands ###
