"""followup engine overdue flags + followup suggestions

Revision ID: 31baf00dce9a
Revises: 0e6fbf22aa84
Create Date: 2026-02-18 18:20:00.900400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31baf00dce9a'
down_revision: Union[str, None] = '0e6fbf22aa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followupsuggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('baseline_days', sa.Integer(), nullable=False),
    sa.Column('days_since_applied', sa.Integer(), nullable=False),
    sa.Column('rule_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followupsuggestion_application_id'), 'followupsuggestion', ['application_id'], unique=False)
    op.create_index(op.f('ix_followupsuggestion_kind'), 'followupsuggestion', ['kind'], unique=False)
    op.create_index(op.f('ix_followupsuggestion_status'), 'followupsuggestion', ['status'], unique=False)
    op.create_index(op.f('ix_followupsuggestion_user_id'), 'followupsuggestion', ['user_id'], unique=False)
    op.add_column('application', sa.Column('is_overdue', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('application', sa.Column('overdue_at', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('overdue_baseline_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'overdue_baseline_days')
    op.drop_column('application', 'overdue_at')
    op.drop_column('application', 'is_overdue')
    op.drop_index(op.f('ix_followupsuggestion_user_id'), table_name='followupsuggestion')
    op.drop_index(op.f('ix_followupsuggestion_status'), table_name='followupsuggestion')
    op.drop_index(op.f('ix_followupsuggestion_kind'), table_name='followupsuggestion')
    op.drop_index(op.f('ix_followupsuggestion_application_id'), table_name='followupsuggestion')
    op.drop_table('followupsuggestion')
    # ### end Alembic commands ###
