"""create core tables

Revision ID: 6986d45539e8
Revises: 
Create Date: 2026-02-17 11:37:02.804816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6986d45539e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version_label', name='uq_resume_user_version')
    )
    op.create_index(op.f('ix_resume_user_id'), 'resume', ['user_id'], unique=False)
    op.create_index(op.f('ix_resume_version_label'), 'resume', ['version_label'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('current_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_url', name='uq_application_user_joburl')
    )
    op.create_index(op.f('ix_application_company_name'), 'application', ['company_name'], unique=False)
    op.create_index(op.f('ix_application_company_type'), 'application', ['company_type'], unique=False)
    op.create_index(op.f('ix_application_current_stage'), 'application', ['current_stage'], unique=False)
    op.create_index(op.f('ix_application_date_applied'), 'application', ['date_applied'], unique=False)
    op.create_index(op.f('ix_application_job_url'), 'application', ['job_url'], unique=False)
    op.create_index(op.f('ix_application_platform'), 'application', ['platform'], unique=False)
    op.create_index(op.f('ix_application_resume_id'), 'application', ['resume_id'], unique=False)
    op.create_index(op.f('ix_application_role_category'), 'application', ['role_category'], unique=False)
    op.create_index(op.f('ix_application_user_id'), 'application', ['user_id'], unique=False)
    op.create_table('applicationstage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicationstage_stage'), 'applicationstage', ['stage'], unique=False)
    op.create_index(op.f('ix_applicationstage_timestamp'), 'applicationstage', ['timestamp'], unique=False)
    op.create_index('ix_stage_app_timestamp', 'applicationstage', ['application_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stage_app_timestamp', table_name='applicationstage')
    op.drop_index(op.f('ix_applicationstage_timestamp'), table_name='applicationstage')
    op.drop_index(op.f('ix_applicationstage_stage'), table_name='applicationstage')
    op.drop_table('applicationstage')
    op.drop_index(op.f('ix_application_user_id'), table_name='application')
    op.drop_index(op.f('ix_application_role_category'), table_name='application')
    op.drop_index(op.f('ix_application_resume_id'), table_name='application')
    op.drop_index(op.f('ix_application_platform'), table_name='application')
    op.drop_index(op.f('ix_application_job_url'), table_name='application')
    op.drop_index(op.f('ix_application_date_applied'), table_name='application')
    op.drop_index(op.f('ix_application_current_stage'), table_name='application')
    op.drop_index(op.f('ix_application_company_type'), table_name='application')
    op.drop_index(op.f('ix_application_company_name'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_resume_version_label'), table_name='resume')
    op.drop_index(op.f('ix_resume_user_id'), table_name='resume')
    op.drop_table('resume')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
